#define SMALL_WEAPON KatibaC
#define STD_WEAPON Katiba
#define GL_WEAPON KatibaGL
#define AR_WEAPON Zafir
#define MMG_WEAPON Navid
#define DMR_WEAPON Rahim
#define LAUNCHER_WEAPON RPG42
#define LAUNCHER_HEAVY_WEAPON TitanAT
#define SNIPER_WEAPON Lynx
